(import
 (gnu packages)

 (kakafarm packages guile-xyz)

 (guix)
 )

(use-package-modules
 autotools
 base
 bash
 bison
 c
 certs
 compression
 curl
 databases
 emacs
 emacs-xyz
 guile
 guile-xyz
 racket
 scheme
 shellutils
 skribilo
 speech
 terminals
 tls
 web
 )

(packages->manifest
 (list
  autoconf
  bash
  bison
  c-intro-and-ref
  curl
  darkhttpd
  emacs
  emacs-ansi
  emacs-benchmark-init
  emacs-buttercup
  emacs-casual-avy
  emacs-casual-calc
  emacs-casual-dired
  emacs-casual-info
  emacs-cider
  emacs-consult
  emacs-corfu
  emacs-corfu-doc
  emacs-darkroom
  emacs-denote
  emacs-dictionary
  emacs-diff-hl
  emacs-direnv
  emacs-eat
  emacs-ef-themes
  emacs-eglot
  emacs-elfeed
  emacs-elfeed-goodies
  emacs-elfeed-org
  emacs-elfeed-protocol
  emacs-elfeed-score
  emacs-elpher
  emacs-ement
  emacs-eval-in-repl-racket
  emacs-flycheck
  emacs-flycheck-haskell
  emacs-flycheck-package
  emacs-fzf
  emacs-geiser-guile
  emacs-geiser-racket
  emacs-geiser-racket
  emacs-ggtags
  emacs-gnosis
  emacs-go-mode
  emacs-greader
  emacs-gruvbox-theme
  emacs-guix
  emacs-helm
  emacs-helpful
  emacs-howm
  emacs-htmlize
  emacs-hyperbole
  emacs-hyperbole
  emacs-iedit
  emacs-jabber
  emacs-magit
  emacs-magit-todos
  emacs-markdown-mode
  emacs-mastodon
  emacs-multi-vterm
  emacs-multiple-cursors
  emacs-next
  emacs-nginx-mode
  emacs-nov-el
  emacs-olivetti
  emacs-orderless
  emacs-org-roam
  emacs-org-transclusion
  emacs-package-build
  emacs-package-lint
  emacs-paredit
  emacs-parinfer-mode
  emacs-peg
  emacs-perspective
  emacs-racket-mode
  emacs-rainbow-blocks
  emacs-rainbow-delimiters
  emacs-request
  emacs-rust-mode
  emacs-scribble-mode
  emacs-sly
  emacs-subed
  emacs-synosaurus
  emacs-tco-el
  emacs-tempel
  emacs-transmission
  emacs-treemacs
  emacs-undo-tree
  emacs-use-package
  emacs-vertico
  emacs-vterm
  emacs-w3m
  emacs-wgrep
  emacs-whitespace-cleanup-mode
  emacs-wisp-mode
  emacs-writeroom
  emacs-yasnippet
  emacs-zotxt
  espeak-ng
  fzf
  fzf-tab
  glibc
  glibc-locales
  gnu-make
  guile-3.0
  guile-ac-d-bus
  guile-clipboard-speaker
  guile-colorized
  guile-config
  guile-fibers
  guile-filesystem
  guile-gnutls
  guile-goblins
  guile-hall
  guile-hoot
  guile-json-4
  guile-lib
  guile-pipe
  guile-png
  guile-reader
  guile-readline
  guile-simple-zmq
  guile-srfi-128
  guile-srfi-133
  guile-srfi-145
  guile-srfi-146
  guile-srfi-158
  guile-srfi-159
  guile-srfi-180
  guile-srfi-189
  guile-srfi-197
  guile-srfi-232
  guile-srfi-234
  guile-srfi-235
  guile-srfi-89
  guile-websocket
  guile-wisp
  guile-zlib
  guilescript
  haunt
  le-certs
  nss-certs
  r7rs-small-texinfo
  racket
  recutils
  sicp
  skribilo
  slib
  zstd
  ))
