;;; -*- lexical-binding: t; -*-

(require 'cl-lib)

(customize-set-value 'elfeed-feeds
                     '(
                       ("https://acdw.casa/feed.xml" acdw activitypub blog craftering)
                       ("https://analognowhere.com/feed/rss.xml" comics pmjv prahou unixsurrealism)
                       ("https://anchor.fm/s/304b0214/podcast/rss" dad dadsanimepodcast noyoushutthefuckupdad podcast)
                       ("https://api.substack.com/feed/podcast/462466.rss" blog foss freesoftware linux lunduke news opensource unix woke)
                       ("https://baty.net/index.xml" blog emacs personal)
                       ("https://bbs.kawa-kun.com/users/gondola/feed.atom" activitypub bbs.kawa-kun.com bot gondola)
                       ("https://beej.us/blog/rss.xml" blog programming)
                       ("https://blog.archive.org/feed/" archive blog internetarchive official)
                       ("https://blog.benoitj.ca/posts/index.xml" benoitj blog craftering personal)
                       ("https://blog.cleancoder.com/atom.xml" blog programming unclebob)
                       ("https://blog.codeberg.org/feeds/all.atom.xml" codeberg)
                       ("https://blog.freespeechextremist.com/feed.rss" blog freesoftwareextremist fse pete)
                       ("https://blog.minetest.net/feed.rss" computergames games launti minetest official)
                       ("https://blog.mwmbl.org/index.xml" mwmbl news official searchengine)
                       ("https://blog.thomasbergheim.com/posts/index.xml" bergheim blog craftering knighthk systemcrafters)
                       ("https://blog.vaxry.net/feed" blog linux)
                       ("https://botsin.space/@mechilim/with_replies.rss" activitypub covid hebrew israel)
                       ("https://bsky.app/profile/did:plc:vwmtku4tfkezcuzutimyg352/rss" atproto bsky emacs microblog)
                       ("https://c.im/@NWengrov.rss" activitypub blog novartza)
                       ("https://calebh.top/feed" blog caleb craftering kolev personal)
                       ("https://cdn.jwz.org/blog/feed/" blog jwz)
                       ("https://chris-hughes.dev/rss" blog craftering)
                       ("https://christerpher.com/feed.xml" blog craftering)
                       ("https://chromefetus.blogspot.com/feeds/posts/default" blog chromefetus comics hansrickheit personal)
                       ("https://chromefetus.thecomicseries.com/rss/" chromefetus comics)
                       ("https://craphound.com/feed" blog coreydoctorow)
                       ("https://critiqueanddigest.substack.com/" aboubakr blog byzantine hussein husseinaboubakrmansour husseinmansour mansour politics woke)
                       ("https://crumbles.blog/atom.xml" blog dpk lisp scheme tech)
                       ("https://crys.site/index.xml" blog crys personal)
                       ("https://davidson.org.il/feed" davidson hebrew news science weizmann)
                       ("https://davidson.weizmann.ac.il/rss.xml" davidson hebrew news science weizmann)
                       ("https://deidetected.com/index.php/comments/feed/" withreplies woke)
                       ("https://deidetected.com/index.php/feed/" woke)
                       ("https://digital-archive.org.il/feed/" culture hanancohen hebrew internet israel)
                       ("https://drewdevault.com/blog/index.xml" blog drewdevault linux programming)
                       ("https://dthompson.us/feed.xml" blog dthompson programming scheme)
                       ("https://eli.thegreenplace.net/feeds/all.atom.xml" blog clang cpp golang personal programming python)
                       ("https://elpa.gnu.org/packages/greader.xml" elpa emacs greader package)
                       ("https://erictopol.substack.com/feed" covid erictopol science)
                       ("https://feeds.transistor.fm/collection-of-jhourneys" jhourney meditation podcast)
                       ("https://forum.systemcrafters.net/latest.rss" forum freesoftware guix linux lisp scheme systemcrafters)
                       ("https://forum.systemcrafters.net/posts.rss" forum freesoftware guix linux lisp scheme systemcrafters)
                       ("https://fosstodon.org/@daviwil.rss" activitypub craftering daviwil systemcrafters)
                       ("https://fosstodon.org/@daviwil/with_replies.rss" activitypub craftering daviwil replies systemcrafters with_replies)
                       ("https://galperel.wordpress.com/feed/" books hebrew israel)
                       ("https://gitlab.com/michelangelo-rodriguez/greader.atom" commits emacs git greader repository)
                       ("https://glenneth.org/feed.xml" blog craftering glenneth)
                       ("https://glenneth.srht.site/feed.xml" blog craftering glenneth)
                       ("https://guix.gnu.org/feeds/blog.atom" guix news official)
                       ("https://hostux.social/@fsfstatus.rss" gnu official status)
                       ("https://hyperboleandahalf.blogspot.com/feeds/posts/default" blog comics)
                       ("https://idlip.github.io/rss.xml" blog craftering)
                       ("https://internet-israel.com/feed/" hebrew internet israel)
                       ("https://irrelevant.org.il/feed" culture hanancohen hebrew internet israel)
                       ("https://jabbo.webdings.de/blog/atom.xml" blog craftering emacs)
                       ("https://jindrichstyrsky.cz/rss-cs.xml" pmjv prahou unixsurrealism)
                       ("https://jindrichstyrsky.cz/rss-en.xml" pmjv prahou unixsurrealism)
                       ("https://kaka.farm/feed.xml" blog self)
                       ("https://kaka.farm/~brownjenkin/feeds/all.atom.xml" blog self)
                       ("https://killsixbilliondemons.com/feed/" comics killsixbilliondemons)
                       ("https://lemmy.sdf.org/feeds/c/unix_surrealism.xml" comics lemmy pmjv prahou sdf unixsurrealism)
                       ("https://lemmy.sdf.org/u/beejjorgensen" beej lemmy sdf)
                       ("https://libera.chat/atom.xml" blog irc liberachat news)
                       ("https://liberal.codeberg.page/atom.xml" blog craftering)
                       ("https://ludic.mataroa.blog/rss/" blog horror it ludic programming)
                       ("https://luis-felipe.gitlab.io/en/feed.atom" blog emacs guile guix luisfilipe personal)
                       ("https://luminousnine.com/feed.xml" blog craftering)
                       ("https://lunduke.substack.com/feed" blog foss freesoftware linux lunduke news opensource unix woke)
                       ("https://luvstarkei.com/feed/" art blog luvstarkei)
                       ("https://masto.ai/@johnsnowproject/with_replies.rss" activitypub corona covid)
                       ("https://mastodon.sdf.org/@beejjorgensen.rss" activitypub beej sdf)
                       ("https://matklad.github.io/feed.xml" blog programming)
                       ("https://matrix.org/atom.xml" matrix official)
                       ("https://me.literatelisp.eu/feed.xml" lisp literatelisp programming scheme)
                       ("https://megananda.org/feed/" blog meditation)
                       ("https://merveilles.town/@prahou.rss" activitypub comics mastodonironcurtain pmjv prahou unixsurrealism)
                       ("https://merveilles.town/tags/unix_surrealism.rss" activitypubtags comics unixsurrealism)
                       ("https://michal.sapka.me/bsd/rss.xml" blog bsd michalsapka unix)
                       ("https://michal.sapka.me/emacs/rss.xml" blog emacs michalsapka unix)
                       ("https://michal.sapka.me/index.xml" blog bsd emacs linux michalsapka unix)
                       ("https://mstdn.social/@erictopol.rss" activitypub covid erictopol science)
                       ("https://mstdn.social/@erictopol/with_replies.rss" activitypub covid erictopol science)
                       ("https://my.gnusolidario.org/feed/" fsf gnu gnuhealth health medicine news official)
                       ("https://nedroid.com/feed" comics nerdroid webcomic)
                       ("https://neocities.org/site/shermysforest.rss" blog comics)
                       ("https://netdinos.wordpress.com/" blog hebrew israel podcast)
                       ("https://newdiscourses.com/feed/" woke)
                       ("https://npov.substack.com/feed" blog wikipedia)
                       ("https://odysee.com/$/rss/@ArkhamReporter:5" arkhamreporter lovecraft video)
                       ("https://olddeuteronomy.github.io/index.xml" blog emacs)
                       ("https://pivot-to-ai.com/feed/" blog llm news nischteinmallugen nischteinmallugenllm pivottoai)
                       ("https://planet.debian.org/rss20.xml" blog debian linux planet)
                       ("https://planet.emacslife.com/atom.xml" emacs emacslife planet)
                       ("https://planet.gnu.org/rss20.xml" blog gnu linux planet)
                       ("https://planet.guix.gnu.org/atom.xml" freesoftware guile guix planet scheme)
                       ("https://planet.scheme.org/atom.xml" lisp planet scheme)
                       ("https://pluralistic.net/feed/" blog coreydoctorow links)
                       ("https://puri.sm/feed/" blog linux news official purism)
                       ("https://purplg.dev/index.xml" blog craftering)
                       ("https://quillette.com/articles/rss/" news quillette woke)
                       ("https://qum.cz/rss.xml" art blog personal pmjv prahou unixsurrealism)
                       ("https://rednosehacker.com/feed/" blog emacs guile lisp programming scheme)
                       ("https://reiddragon.neocities.org/blog/feed.rss" blog nickname_reid personal reid unixsurrealism)
                       ("https://retropikzel.kapsi.fi/feed.xml" blog craftering)
                       ("https://richarddavis.xyz/en/blog/rss.xml" blog craftering)
                       ("https://rotter.net/rss/rotternews.xml" hebrew israel news rotter)
                       ("https://rss.art19.com/ten-percent-happier" meditation podcast)
                       ("https://samharris.substack.com/feed" blog samharris)
                       ("https://sciencewtg.substack.com/feed" blog popsci sabine sabinehossenfelder science)
                       ("https://scottaaronson.blog/?feed=rss2" blog personal)
                       ("https://sfba.social/@danielmingram/with_replies.rss" activitypub danielmingram)
                       ("https://shakuf.co.il/feed" hebrew israel news shakuf)
                       ("https://shom.dev/index.xml" blog craftering linux)
                       ("https://snac.lab8.cz/js.rss" pmjv prahou triapul unixsurrealism)
                       ("https://speechcode.com/blog/rss" arthuragleckler blog lisp personal scheme srfi)
                       ("https://spritely.institute/feed.xml" goblins hoot linux lisp official scheme spritely)
                       ("https://sr.ht/~abcdw/rde-monthly/feed.rss" guix lisp newsletter rde scheme)
                       ("https://stallmansupport.org/feed.xml" richardmathewstallman rms stallman woke)
                       ("https://status.mangadex.org/history.atom" comics)
                       ("https://summeremacs.github.io/index.xml" blog craftering emacs lisp programming scheme summeremacs unix)
                       ("https://systemcrafters.net/rss/news.xml" blog craftering emacs guile guix linux lisp news official scheme)
                       ("https://tdback.net/index.xml" blog craftering)
                       ("https://thanosapollo.org/index.xml" blog craftering)
                       ("https://tilde.town/~ramin_hal9001/atom.xml" blog lisp programming raminhonary scheme)
                       ("https://tomerpersico.com/feed/" blog hebrew personal religion)
                       ("https://tooot.im/@NWengrov.rss" activitypub blog novartza)
                       ("https://tooot.im/@admin.rss" activitypub admin blog official)
                       ("https://torrentfreak.com/feed/" blog filesharing internet news pirating torrents)
                       ("https://trevarj.github.io/rss.xml" blog craftering)
                       ("https://triapul.cz/feed/cesky.xml" blog cesky computing czech pmjv prahou triapul unix unixsurrealism)
                       ("https://triapul.cz/feed/english.xml" blog computing pmjv prahou triapul unix unixsurrealism)
                       ("https://triapul.cz/feed/gopher.xml" blog computing gopher pmjv prahou triapul unix unixsurrealism)
                       ("https://tusharhero.codeberg.page/rss.xml" blog craftering)
                       ("https://tylerdback.com/index.xml" blog craftering)
                       ("https://unixdigest.com/feed.rss" blog linux news unix)
                       ("https://vimeo.com/user13532867/videos/rss" danielmingram meditation video)
                       ("https://weinholt.se/feed.xml" blog personal scheme weinholt)
                       ("https://whatsup.org.il/backend-forums.php?utf8=1" forum hebrew israel linux whatsup)
                       ("https://whatsup.org.il/backend.php?utf8=1" forum hebrew israel linux whatsup)
                       ("https://whhone.com/index.xml" blog emacs freesoftware linux programming waihon)
                       ("https://world.hey.com/dhh/feed.atom" blog dhh omarchy woke)
                       ("https://write.as/jeko/feed/" blog guile lisp personal programming scheme)
                       ("https://www.accursedfarms.com/rss/3-accursed-farms.xml/" accursedfarms blog rossscott video)
                       ("https://www.andrewgoldheretics.com/feed" andrewgold blog woke)
                       ("https://www.astralcodexten.com/feed" astralcodexten blog woke)
                       ("https://www.blipanika.co.il/?feed=rss2" hebrew israel scifi)
                       ("https://www.debian.org/News/news" debian linux news official)
                       ("https://www.futurile.net/feeds/all.atom.xml" blog futurile guile guix personal programming stevegeorge)
                       ("https://www.gnu.org/software/shepherd/news/feed.xml" freesoftware gnu official shepherd)
                       ("https://www.goominet.com/unspeakable-vault/?type=103" comics)
                       ("https://www.greenpeace.org/israel/rss" blog environmentalism greenpeace news official)
                       ("https://www.ha-makom.co.il/feed/" hamakom hebrew israel news)
                       ("https://www.hayadan.org.il/feed" hayadan hebrew news science)
                       ("https://www.jesusandmo.net/feed/atom/" atheism comics)
                       ("https://www.jhourney.io/blog?format=rss" blog jhana jhourney meditation)
                       ("https://www.joanwestenberg.com/rss/" blog personal)
                       ("https://www.kukuruyo.com/feed/" comics kukuruyo webcomic)
                       ("https://www.linux.com/feed/" blog linux)
                       ("https://www.livejournal.com/allpics.bml?user=oglafcomics" comics)
                       ("https://www.messynessychic.com/feed/" blog curios messynessy)
                       ("https://www.midaat.org.il/feed/" conspiracy medicine midaat science)
                       ("https://www.more-magic.net/feed.atom" blog computing lisp programming scheme unix)
                       ("https://www.ngocomment.com/feed" andyngo antifa blog news)
                       ("https://www.okmij.org/ftp/atom.xml" blog okmij personal programming scheme)
                       ("https://www.okmij.org/ftp/rss.xml" blog okmij personal programming scheme)
                       ("https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/cf0c25ad-cf01-4da5-ae1c-b0fc015f790e/53ed270b-7147-4f70-81c2-b0fc015fe4ed/podcast.rss" betteroffline edzitron llm podcast)
                       ("https://www.rahuljuliato.com/rss.xml" blog craftering)
                       ("https://www.realityslaststand.com/feed" blog popsci woke)
                       ("https://www.rifters.com/crawl/?feed=rss2" blog peterwatts scifi)
                       ("https://www.schneier.com/feed/atom/" blog news personal schneier security)
                       ("https://www.sexylosers.com/feed/" comics sexylosers)
                       ("https://www.snamellit.com/rss.xml" blog craftering)
                       ("https://www.the7eye.org.il/feed" hebrew israel news the7eye)
                       ("https://www.webster.co.il/feed/" blog hanancohen hebrew israel)
                       ("https://www.wheresyoured.at/rss/" blog news tech)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UC4fQ-Cy8UpLPMwehPg-8ltQ" andrewgold podcast video woke youtube)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UC4kLp84DGlsPz-a85gK-zng" gadyair hebrew video woke youtube)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UChhBwFmg5celKNf_naIotEA" rants raz video void woke youtube)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UCkK9UDm_ZNrq_rIXCz3xCGA" blog foss freesoftware linux lunduke news opensource unix video woke youtube)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UCv8koFYj7W0edfShn3eCz8A" rants raz video void woke youtube)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UCzREuchzOqiawpEpvEM0Tyg" atheism islam video youtube)
                       ("https://xonotic.org/index.xml" blog computergames games official xonotic)
                       ("https://ziglang.org/devlog/index.xml" blog news official programming ziglang)
                       ))

(let ((path (locate-user-emacs-file "local-elfeed-feeds.el")))
  (when (file-exists-p path) (load path)))
