(require 'cl-lib)

(setq elfeed-feeds
      '(("https://acdw.casa/feed.xml" acdw activitypub blog craftering)
        ("https://analognowhere.com/feed/rss.xml" comics unixsurrealism)
        ("https://beej.us/blog/rss.xml" blog programming)
        ("https://blog.benoitj.ca/posts/index.xml" blog craftering)
        ("https://blog.codeberg.org/feeds/all.atom.xml" codeberg)
        ("https://blog.vaxry.net/feed" blog linux)
        ("https://botsin.space/@mechilim/with_replies.rss" activitypub covid israel)
        ("https://c.im/@NWengrov.rss" activitypub blog novartza)
        ("https://cdn.jwz.org/blog/feed/" blog jwz)
        ("https://chris-hughes.dev/rss" blog craftering)
        ("https://christerpher.com/feed.xml" blog craftering)
        ("https://chromefetus.thecomicseries.com/rss/" chromefetus comics)
        ("https://davidson.weizmann.ac.il/rss.xml" davidson news science weizmann)
        ("https://deidetected.com/index.php/comments/feed/" csj withreplies)
        ("https://deidetected.com/index.php/feed/" csj)
        ("https://drewdevault.com/blog/index.xml" blog drewdevault linux programming)
        ("https://erictopol.substack.com/feed" covid erictopol science)
        ("https://galperel.wordpress.com/feed/" books hebrew israel)
        ("https://glenneth.srht.site/feed.xml" blog craftering)
        ("https://hyperboleandahalf.blogspot.com/feeds/posts/default" blog comics)
        ("https://internet-israel.com/feed/" internet israel)
        ("https://kaka.farm/haunt/feed.xml" blog craftering self)
        ("https://kaka.farm/~brownjenkin/feeds/all.atom.xml" blog self)
        ("https://lemmy.sdf.org/feeds/c/unix_surrealism.xml" comics lemmy sdf unixsurrealism)
        ("https://lemmy.sdf.org/u/beejjorgensen" beej lemmy sdf)
        ("https://libera.chat/atom.xml" blog irc liberachat news)
        ("https://luminousnine.com/feed.xml" blog craftering)
        ("https://masto.ai/@johnsnowproject/with_replies.rss" activitypub corona covid)
        ("https://mastodon.sdf.org/@beejjorgensen.rss" activitypub beej sdf)
        ("https://megananda.org/comments/feed/" blog comments meditation)
        ("https://megananda.org/feed/" blog meditation)
        ("https://merveilles.town/tags/unix_surrealism.rss" comics unixsurrealism)
        ("https://michal.sapka.me/bsd/rss.xml" blog bsd michalsapka unix)
        ("https://michal.sapka.me/emacs/rss.xml" blog emacs michalsapka unix)
        ("https://michal.sapka.me/index.xml" blog bsd emacs linux michalsapka unix)
        ("https://mstdn.social/@erictopol.rss" activitypub covid erictopol science)
        ("https://mstdn.social/@erictopol/with_replies.rss" activitypub covid erictopol science)
        ("https://newdiscourses.com/feed/" csj)
        ("https://odysee.com/$/rss/@ArkhamReporter:5" arkhamreporter lovecraft video)
        ("https://planet.debian.org/rss20.xml" blog debian linux)
        ("https://planet.scheme.org/atom.xml" lisp planet scheme)
        ("https://puri.sm/feed/" linux purism)
        ("https://purplg.dev/index.xml" blog craftering)
        ("https://richarddavis.xyz/en/blog/rss.xml" blog craftering)
        ("https://rss.art19.com/ten-percent-happier" meditation podcast)
        ("https://samharris.substack.com/feed" blog samharris)
        ("https://sfba.social/@danielmingram/with_replies.rss" activitypub danielmingram)
        ("https://shakuf.co.il/feed" israel news shakuf)
        ("https://shom.dev/index.xml" blog craftering linux)
        ("https://spritely.institute/feed.xml" linux lisp scheme)
        ("https://sr.ht/~abcdw/rde-monthly/feed.rss" guix lisp newsletter scheme)
        ("https://status.mangadex.org/history.atom" comics)
        ("https://systemcrafters.net/rss/news.xml" blog craftering emacs guile guix linux lisp news scheme)
        ("https://thanosapollo.org/index.xml" blog craftering)
        ("https://tooot.im/@NWengrov.rss" activitypub blog novartza)
        ("https://tooot.im/@admin.rss" activitypub admin)
        ("https://torrentfreak.com/feed/" filesharing internet news pirating torrents)
        ("https://trevarj.github.io/rss.xml" blog craftering)
        ("https://tylerdback.com/index.xml" blog craftering)
        ("https://vimeo.com/user13532867/videos/rss" danielmingram meditation)
        ("https://whatsup.org.il/backend-forums.php?utf8=1" israel linux whatsup)
        ("https://whatsup.org.il/backend.php?utf8=1" israel linux whatsup)
        ("https://www.accursedfarms.com/rss/3-accursed-farms.xml/" accursedfarms blog)
        ("https://www.blipanika.co.il/?feed=rss2" israel scifi)
        ("https://www.debian.org/News/news" debian linux news)
        ("https://www.goominet.com/unspeakable-vault/?type=103" comics)
        ("https://www.ha-makom.co.il/feed/" hamakom israel news)
        ("https://www.hayadan.org.il/feed" hayadan news science)
        ("https://www.linux.com/feed/" linux)
        ("https://www.livejournal.com/allpics.bml?user=oglafcomics" comics)
        ("https://www.midaat.org.il/feed/" conspiracy medicine midaat science)
        ("https://www.rahuljuliato.com/rss.xml" blog craftering)
        ("https://www.realityslaststand.com/feed" csj popsci)
        ("https://www.rifters.com/crawl/?feed=rss2" blog peterwatts scifi)
        ("https://www.snamellit.com/rss.xml" blog craftering)
        ("https://www.the7eye.org.il/feed" israel news the7eye)
        ("https://www.wheresyoured.at/rss/" blog news tech)))

(setq elfeed-feeds
      (kakafarm/elfeed-sort-feeds
       (add-to-list 'elfeed-feeds
                    (list (concat "https://rss.samharris.org/feed/"
                                  kakafarm/elfeed-making-sense-with-sam-harris-podcast-secret-feed-key)
                          'podcast 'samharris))))
