(require 'cl-lib)

(customize-set-value 'elfeed-feeds
                     '(
                       ("https://acdw.casa/feed.xml" acdw activitypub blog craftering)
                       ("https://analognowhere.com/feed/rss.xml" comics unixsurrealism)
                       ("https://api.substack.com/feed/podcast/462466.rss" blog foss freesoftware linux lunduke news opensource unix)
                       ("https://beej.us/blog/rss.xml" blog programming)
                       ("https://blog.benoitj.ca/posts/index.xml" blog craftering)
                       ("https://blog.cleancoder.com/atom.xml" blog programming unclebob)
                       ("https://blog.codeberg.org/feeds/all.atom.xml" codeberg)
                       ("https://blog.mwmbl.org/index.xml" mwmbl news official searchengine)
                       ("https://blog.vaxry.net/feed" blog linux)
                       ("https://botsin.space/@mechilim/with_replies.rss" activitypub covid hebrew israel)
                       ("https://c.im/@NWengrov.rss" activitypub blog novartza)
                       ("https://cdn.jwz.org/blog/feed/" blog jwz)
                       ("https://chris-hughes.dev/rss" blog craftering)
                       ("https://christerpher.com/feed.xml" blog craftering)
                       ("https://chromefetus.thecomicseries.com/rss/" chromefetus comics)
                       ("https://davidson.weizmann.ac.il/rss.xml" davidson news science weizmann)
                       ("https://deidetected.com/index.php/comments/feed/" csj withreplies)
                       ("https://deidetected.com/index.php/feed/" csj)
                       ("https://digital-archive.org.il/feed/" culture hanancohen hebrew internet israel)
                       ("https://drewdevault.com/blog/index.xml" blog drewdevault linux programming)
                       ("https://dthompson.us/feed.xml" blog dthompson programming scheme)
                       ("https://elpa.gnu.org/packages/greader.xml" elpa emacs greader package)
                       ("https://erictopol.substack.com/feed" covid erictopol science)
                       ("https://feeds.transistor.fm/collection-of-jhourneys" jhourney meditation podcast)
                       ("https://forum.systemcrafters.net/latest.rss" forum freesoftware guix linux lisp scheme systemcrafters)
                       ("https://forum.systemcrafters.net/posts.rss" forum freesoftware guix linux lisp scheme systemcrafters)
                       ("https://galperel.wordpress.com/feed/" books hebrew israel)
                       ("https://gitlab.com/michelangelo-rodriguez/greader.atom" commits emacs git greader repository)
                       ("https://glenneth.srht.site/feed.xml" blog craftering)
                       ("https://guix.gnu.org/feeds/blog.atom" guix news official)
                       ("https://hostux.social/@fsfstatus.rss" gnu official status)
                       ("https://hyperboleandahalf.blogspot.com/feeds/posts/default" blog comics)
                       ("https://idlip.github.io/rss.xml" blog craftering)
                       ("https://internet-israel.com/feed/" internet hebrew israel)
                       ("https://irrelevant.org.il/feed" culture hanancohen hebrew internet israel)
                       ("https://jabbo.webdings.de/blog/atom.xml" blog craftering emacs)
                       ("https://kaka.farm/feed.xml" blog craftering self)
                       ("https://kaka.farm/~brownjenkin/feeds/all.atom.xml" blog self)
                       ("https://killsixbilliondemons.com/feed/" comics killsixbilliondemons)
                       ("https://lemmy.sdf.org/feeds/c/unix_surrealism.xml" comics lemmy sdf unixsurrealism)
                       ("https://lemmy.sdf.org/u/beejjorgensen" beej lemmy sdf)
                       ("https://libera.chat/atom.xml" blog irc liberachat news)
                       ("https://ludic.mataroa.blog/rss/" blog horror it ludic programming)
                       ("https://luminousnine.com/feed.xml" blog craftering)
                       ("https://luvstarkei.com/feed/" art blog luvstarkei)
                       ("https://masto.ai/@johnsnowproject/with_replies.rss" activitypub corona covid)
                       ("https://mastodon.sdf.org/@beejjorgensen.rss" activitypub beej sdf)
                       ("https://matklad.github.io/feed.xml" blog programming)
                       ("https://me.literatelisp.eu/feed.xml" lisp literatelisp programming scheme)
                       ("https://megananda.org/feed/" blog meditation)
                       ("https://merveilles.town/tags/unix_surrealism.rss" comics unixsurrealism)
                       ("https://michal.sapka.me/bsd/rss.xml" blog bsd michalsapka unix)
                       ("https://michal.sapka.me/emacs/rss.xml" blog emacs michalsapka unix)
                       ("https://michal.sapka.me/index.xml" blog bsd emacs linux michalsapka unix)
                       ("https://mstdn.social/@erictopol.rss" activitypub covid erictopol science)
                       ("https://mstdn.social/@erictopol/with_replies.rss" activitypub covid erictopol science)
                       ("https://my.gnusolidario.org/feed/" fsf gnu gnuhealth health medicine news official)
                       ("https://nedroid.com/feed" comics nerdroid webcomic)
                       ("https://newdiscourses.com/feed/" csj)
                       ("https://odysee.com/$/rss/@ArkhamReporter:5" arkhamreporter lovecraft video)
                       ("https://olddeuteronomy.github.io/index.xml" blog emacs rip thisguydisappearedofftheinternethowsad)
                       ("https://planet.debian.org/rss20.xml" blog debian linux planet)
                       ("https://planet.emacslife.com/atom.xml" emacs emacslife planet)
                       ("https://planet.gnu.org/rss20.xml" blog gnu linux planet)
                       ("https://planet.scheme.org/atom.xml" lisp planet scheme)
                       ("https://puri.sm/feed/" linux news official purism)
                       ("https://purplg.dev/index.xml" blog craftering)
                       ("https://rednosehacker.com/feed/" blog emacs guile lisp programming scheme)
                       ("https://reiddragon.neocities.org/blog/feed.rss" blog nickname_reid unix_surrealism)
                       ("https://retropikzel.kapsi.fi/feed.xml" blog craftering)
                       ("https://richarddavis.xyz/en/blog/rss.xml" blog craftering)
                       ("https://rotter.net/rss/rotternews.xml" hebrew israel news rotter)
                       ("https://rss.art19.com/ten-percent-happier" meditation podcast)
                       ("https://samharris.substack.com/feed" blog samharris)
                       ("https://sfba.social/@danielmingram/with_replies.rss" activitypub danielmingram)
                       ("https://shakuf.co.il/feed" hebrew israel news shakuf)
                       ("https://shom.dev/index.xml" blog craftering linux)
                       ("https://spritely.institute/feed.xml" linux lisp official scheme)
                       ("https://sr.ht/~abcdw/rde-monthly/feed.rss" guix lisp newsletter rde scheme)
                       ("https://status.mangadex.org/history.atom" comics)
                       ("https://summeremacs.github.io/index.xml" blog craftering emacs lisp programming scheme summeremacs unix)
                       ("https://systemcrafters.net/rss/news.xml" blog craftering emacs guile guix linux lisp news official scheme)
                       ("https://tdback.net/index.xml" blog craftering)
                       ("https://thanosapollo.org/index.xml" blog craftering)
                       ("https://tilde.town/~ramin_hal9001/atom.xml" blog lisp programming raminhonary scheme)
                       ("https://tooot.im/@NWengrov.rss" activitypub blog novartza)
                       ("https://tooot.im/@admin.rss" activitypub admin)
                       ("https://torrentfreak.com/feed/" filesharing internet news pirating torrents)
                       ("https://trevarj.github.io/rss.xml" blog craftering)
                       ("https://triapul.cz/feed/cesky.xml" blog cesky computing czech unix unixsurrealism)
                       ("https://triapul.cz/feed/english.xml" blog computing unix unixsurrealism)
                       ("https://triapul.cz/feed/gopher.xml" blog computing gopher unix unixsurrealism)
                       ("https://tusharhero.codeberg.page/rss.xml" blog craftering)
                       ("https://tylerdback.com/index.xml" blog craftering)
                       ("https://unixdigest.com/feed.rss" blog linux news unix unix)
                       ("https://vimeo.com/user13532867/videos/rss" danielmingram meditation)
                       ("https://whatsup.org.il/backend-forums.php?utf8=1" hebrew israel linux whatsup)
                       ("https://whatsup.org.il/backend.php?utf8=1" hebrew israel linux whatsup)
                       ("https://www.accursedfarms.com/rss/3-accursed-farms.xml/" accursedfarms blog)
                       ("https://www.andrewgoldheretics.com/feed" andrewgold blog csj)
                       ("https://www.astralcodexten.com/feed" astralcodexten blog csj)
                       ("https://www.blipanika.co.il/?feed=rss2" hebrew israel scifi)
                       ("https://www.debian.org/News/news" debian linux news)
                       ("https://www.goominet.com/unspeakable-vault/?type=103" comics)
                       ("https://www.ha-makom.co.il/feed/" hamakom hebrew israel news)
                       ("https://www.hayadan.org.il/feed" hayadan hebrew news science)
                       ("https://www.jhourney.io/blog?format=rss" blog jhana jhourney meditation)
                       ("https://www.kukuruyo.com/feed/" comics kukuruyo webcomic)
                       ("https://www.linux.com/feed/" linux)
                       ("https://www.livejournal.com/allpics.bml?user=oglafcomics" comics)
                       ("https://www.midaat.org.il/feed/" conspiracy medicine midaat science)
                       ("https://www.more-magic.net/feed.atom" blog computing lisp programming scheme unix)
                       ("https://www.rahuljuliato.com/rss.xml" blog craftering)
                       ("https://www.realityslaststand.com/feed" csj popsci)
                       ("https://www.rifters.com/crawl/?feed=rss2" blog peterwatts scifi)
                       ("https://www.sexylosers.com/feed/" comics sexylosers)
                       ("https://www.snamellit.com/rss.xml" blog craftering)
                       ("https://www.the7eye.org.il/feed" hebrew israel news the7eye)
                       ("https://www.webster.co.il/feed/" blog hanancohen hebrew israel)
                       ("https://www.wheresyoured.at/rss/" blog news tech)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UC4fQ-Cy8UpLPMwehPg-8ltQ" andrewgold csj podcast video youtube)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UC4kLp84DGlsPz-a85gK-zng" csj gadyair hebrew video youtube)
                       ("https://www.youtube.com/feeds/videos.xml?channel_id=UCzREuchzOqiawpEpvEM0Tyg" atheism islam video youtube)
                       ))
